workspace:
  base: /test
  path: oe_authentication

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
     - DOCUMENT_ROOT=/test/oe_authentication
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  authentication:
    image: registry.fpfis.tech.ec.europa.eu/ecas-mock-server:4.6.0
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
    # @todo remove "composer install" step once the following issue is fixed.
    # @link https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
    - composer install --ansi --no-suggest --no-progress
    - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      # Setup to use eCAS-mockup server.
      - ./vendor/bin/run setup:ecas-mockup
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      # Reset permission since installation runs as root. @todo Fix this.
      - ./vendor/bin/drush -y config-set system.performance css.preprocess 0
      - ./vendor/bin/drush -y config-set system.performance js.preprocess 0
      - ./vendor/bin/behat

matrix:
  COMPOSER_BOUNDARY:
  - lowest
  - highest
