<?php

/**
 * @file
 * OpenEuropa Authentication module.
 */

declare(strict_types = 1);

/**
 * Implements hook_user_cancel_methods_alter().
 *
 * Remove the option to delete users while keeping the option to block them.
 */
function oe_authentication_user_cancel_methods_alter(&$methods) {
  $user = \Drupal::currentUser();
  if (!$user->hasPermission('delete user')) {
    $restricted_options = [
      'user_cancel_reassign',
      'user_cancel_delete',
    ];
    foreach ($restricted_options as $restricted_option) {
      unset($methods[$restricted_option]);
    }
  }
}
